name: Backend-CD

on:
  workflow_run:
    workflows: ["Backend-CI"]
    types:
      - completed
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Backend to Render
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: backend-ci.yml
          workflow_conclusion: success
          name: backend-jar
          path: ./teleheal-backend/build/libs/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create production Dockerfile
        run: |
          echo "FROM openjdk:24-jdk-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY ./teleheal-backend/build/libs/teleheal-backend-0.0.1-SNAPSHOT.jar app.jar" >> Dockerfile    
          echo "EXPOSE 8080" >> Dockerfile
          echo 'CMD ["java", "-jar", "app.jar"]' >> Dockerfile    

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/teleheal-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/teleheal-backend:${{ github.sha }}

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "::notice::Triggering Render deployment"
          curl -X GET "https://api.render.com/deploy/$RENDER_SERVICE_ID?key=$RENDER_API_KEY"
          echo "::notice::Deployment triggered successfully"
