name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'teleheal-backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'teleheal-backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./teleheal-backend/gradlew

      - name: Build with Gradle
        run: |
          cd teleheal-backend
          ./gradlew build

      # Upload the built jar as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: teleheal-backend/build/libs/
          retention-days: 1

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/teleheal-backend/build/test-results/test/TEST-*.xml"
          check_name: "Backend Test Results"
          comment_mode: "always"
          fail_on: "nothing"
          report_individual_runs: true
          check_run_annotations: "all tests"
          github_token: ${{ secrets.GITHUB_TOKEN }}
