name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run security scans weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  backend-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./teleheal-backend/gradlew
      
    - name: Run OWASP Dependency Check
      run: |
        cd teleheal-backend
        ./gradlew dependencyCheckAnalyze || true
        
    - name: Upload OWASP Dependency Check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-dependency-check-report
        path: teleheal-backend/build/reports/
        retention-days: 30

  frontend-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: teleheal-ui/package-lock.json
        
    - name: Install dependencies
      run: |
        cd teleheal-ui
        npm ci
        
    - name: Run npm audit
      run: |
        cd teleheal-ui
        npm audit --audit-level=moderate || true
        
    - name: Run npm audit fix
      run: |
        cd teleheal-ui
        npm audit fix --dry-run || true

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        
    - name: Set up JDK 24 (for Java analysis)
      if: matrix.language == 'java'
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        
    - name: Build Java project (for CodeQL)
      if: matrix.language == 'java'
      run: |
        cd teleheal-backend
        chmod +x gradlew
        ./gradlew build -x test
        
    - name: Set up Node.js (for JavaScript analysis)
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: teleheal-ui/package-lock.json
        
    - name: Build JavaScript project (for CodeQL)
      if: matrix.language == 'javascript'
      run: |
        cd teleheal-ui
        npm ci
        npm run build
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
